#!/bin/bash

# sysinfo - display summary of system information
#   note: designed for RHEL/CentOS systems
#
#   Taken from a script I found online and modified
# extra comment line

b=$(tput bold)
n=$(tput sgr0)
echo -e "${b}Hostname:${n} $(hostname)"
echo -e "${b}OS Version:${n} $(cat /etc/redhat-release)"
echo -e "${b}Kernel:${n} $(uname -rv)"
echo
echo -e "${b}IP address(es):${n}\n$(/sbin/ifconfig | grep "inet " | awk '{print $2}' | sed 's/addr://' | sort -n | awk -F'.' '{ printf("%3d.%3d.%3d.%3d\n", $1, $2, $3, $4) }')"
echo
echo -e "${b}CPU load:${n} $(cut -d" " -f1-3 /proc/loadavg) \t ${b}Proccesses (running/total):${n} $(awk '{print $4}' /proc/loadavg)"
echo -e "${b}Free memorry:${n} $(grep MemFree /proc/meminfo | awk \{'print int($2/1024)'\}) MB \t\t ${b}Total memory:${n} $(grep MemTotal /proc/meminfo  | awk \{'print int($2/1024)'\}) MB"
echo -e "${b}Uptime:${n} $(uptime | sed 's/\(.*\),.*,.*,.*,.*/\1/' | sed 's/.*up *//')"
echo
echo -e "${b}Active sessions:${n}\n$(w | tail -n +2)"
echo
