#!/bin/bash

# sysinfo - display summary of system information
#   note: designed for RHEL/CentOS systems
#
#   Taken from a script I found online and modified


b=`tput bold`
n=`tput sgr0`
echo -e "${b}Hostname:${n} `hostname`"
echo -e "${b}OS Version:${n} `cat /etc/redhat-release`\n"
echo -e "${b}IP address(es):${n}\n`/sbin/ifconfig | grep "inet " | awk '{print $2}' | sort -n`\n"
echo -e "${b}CPU load:${n} `cat /proc/loadavg | cut -d" " -f1-3`"
echo -e "${b}Uptime:${n} `uptime | sed 's/\(.*\),.*,.*,.*,.*/\1/' | sed 's/.*up *//'`"
echo -e "${b}Free memorry:${n} `cat /proc/meminfo | grep MemFree | awk {'print int($2/1024)'}` MB \t\t Total memory: `cat /proc/meminfo | grep MemTotal | awk {'print int($2/1000)'}` MB"
echo -e "${b}Proccess number:${n} `cat /proc/loadavg | cut -d"/" -f2| cut -d" " -f1`\n"
echo -e "${b}Active sessions:${n}\n`w | tail -n +2`\n"
